[versions]
agp = "8.13.0"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
appcompatVersion = "1.7.1"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

